In [1]:
import pandas as pd

dataset1 = pd.read_csv('Transaction_Data (1).csv')

In [2]:
print(dataset1.head())

   Transaction_ID  Customer_ID     Transaction_Date  Transaction_Amount  \
0               1          393  2023-01-01 00:00:00              3472.0
1               2          826  2023-01-01 01:00:00                 NaN
2               3          916  2023-01-01 02:00:00                10.0
3               4          109  2023-01-01 03:00:00                72.0
4               5          889  2023-01-01 04:00:00              1793.0

  Transaction_Type
0         Purchase
1     Bill Payment
2         Purchase
3       Investment
4       Investment

In [3]:
print(dataset1.isnull().sum())

Transaction_ID          0
Customer_ID             0
Transaction_Date        0
Transaction_Amount    100
Transaction_Type        0
dtype: int64

In [4]:
dataset1 = dataset1.drop(columns=['Transaction_Amount'])

In [5]:
dataset1 = dataset1.drop_duplicates()

In [6]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

dataset1['Transaction_Type'] = label_encoder.fit_transform(dataset1['Transaction_Type'])

dataset1

      Transaction_ID  Customer_ID     Transaction_Date  Transaction_Type
0                  1          393  2023-01-01 00:00:00                 3
1                  2          826  2023-01-01 01:00:00                 0
2                  3          916  2023-01-01 02:00:00                 3
3                  4          109  2023-01-01 03:00:00                 1
4                  5          889  2023-01-01 04:00:00                 1
...              ...          ...                  ...               ...
4995            4996          175  2023-07-28 03:00:00                 1
4996            4997          338  2023-07-28 04:00:00                 0
4997            4998          694  2023-07-28 05:00:00                 0
4998            4999          940  2023-07-28 06:00:00                 3
4999            5000          353  2023-07-28 07:00:00                 1

[5000 rows x 4 columns]

Label Encoding has been applied to the 'Transaction_Type' column.

In [7]:
dataset1['Transaction_Hour'] = pd.to_datetime(dataset1['Transaction_Date']).dt.hour

dataset1['Transaction_DayOfWeek'] = pd.to_datetime(dataset1['Transaction_Date']).dt.dayofweek


dataset1['Transaction_WeekPart'] = dataset1['Transaction_DayOfWeek'].apply(lambda x: 'Weekend' if x >= 5 else 'Weekday')

dataset1['Transaction_WeekPart'] = label_encoder.fit_transform(dataset1['Transaction_WeekPart'])

dataset1

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Transaction_Hour,Transaction_DayOfWeek,Transaction_WeekPart
0,1,393,2023-01-01 00:00:00,3,0,6,1
1,2,826,2023-01-01 01:00:00,0,1,6,1
2,3,916,2023-01-01 02:00:00,3,2,6,1
3,4,109,2023-01-01 03:00:00,1,3,6,1
4,5,889,2023-01-01 04:00:00,1,4,6,1
...,...,...,...,...,...,...,...
4995,4996,175,2023-07-28 03:00:00,1,3,4,0
4996,4997,338,2023-07-28 04:00:00,0,4,4,0
4997,4998,694,2023-07-28 05:00:00,0,5,4,0
4998,4999,940,2023-07-28 06:00:00,3,6,4,0
4999,5000,353,2023-07-28 07:00:00,1,7,4,0

New features have been created: 
1. `Transaction_Hour`: Extracted hour of the transaction.
2. `Transaction_DayOfWeek`: Day of the week (0=Monday, 6=Sunday).
3. `Transaction_WeekPart`: Categorized as 'Weekday' or 'Weekend' (encoded).

In [8]:
# Splitting the dataset into features (X) and target (y)
X = dataset1.drop(columns=['Transaction_Type'])
y = dataset1['Transaction_Type']

X, y

(      Transaction_ID  Customer_ID     Transaction_Date  Transaction_Hour  \
 0                  1          393  2023-01-01 00:00:00                 0
 1                  2          826  2023-01-01 01:00:00                 1
 2                  3          916  2023-01-01 02:00:00                 2
 3                  4          109  2023-01-01 03:00:00                 3
 4                  5          889  2023-01-01 04:00:00                 4
 ...              ...          ...                  ...               ...
 4995            4996          175  2023-07-28 03:00:00                 3
 4996            4997          338  2023-07-28 04:00:00                 4
 4997            4998          694  2023-07-28 05:00:00                 5
 4998            4999          940  2023-07-28 06:00:00                 6
 4999            5000          353  2023-07-28 07:00:00                 7

       Transaction_DayOfWeek  Transaction_WeekPart
 0                         6                     1
 1                         6                     1
 2                         6                     1
 3                         6                     1
 4                         6                     1
 ...                     ...                   ...
 4995                      4                     0
 4996                      4                     0
 4997                      4                     0
 4998                      4                     0
 4999                      4                     0

 [5000 rows x 6 columns],
 0       3
 1       0
 2       3
 3       1
 4       1
        ..
 4995    1
 4996    0
 4997    0
 4998    3
 4999    1
 Name: Transaction_Type, Length: 5000, dtype: int64)

The dataset has been successfully split into features (X) and target (y).

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=9f7438eb-a69f-4bf2-a212-4a135e641139' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>